/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ShareWeChatPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  includeTitle: true,
  stripFrontmatter: true,
  resolveWikiLinks: true,
  addSourceTag: false,
  serverUrl: "https://nas.vonxz.cn",
  defaultExpiryDays: 7
};
var ShareWeChatPlugin = class extends import_obsidian.Plugin {
  async onload() {
    await this.loadSettings();
    this.addRibbonIcon("share-2", "\u5206\u4EAB\u5230\u5FAE\u4FE1", () => {
      this.shareCurrentNote();
    });
    this.addCommand({
      id: "share-to-wechat",
      name: "\u5206\u4EAB\u5230\u5FAE\u4FE1",
      icon: "share-2",
      callback: () => this.shareCurrentNote()
    });
    this.addCommand({
      id: "copy-for-wechat",
      name: "\u590D\u5236\u7B14\u8BB0\uFF08\u5FAE\u4FE1\u5206\u4EAB\u683C\u5F0F\uFF09",
      callback: () => this.copyForWeChat()
    });
    this.addCommand({
      id: "share-as-online-card",
      name: "\u5206\u4EAB\u4E3A\u5728\u7EBF\u5361\u7247",
      icon: "globe",
      callback: () => this.shareAsOnlineCard()
    });
    this.addSettingTab(new ShareWeChatSettingTab(this.app, this));
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  getActiveContent() {
    const view = this.app.workspace.getActiveViewOfType(import_obsidian.MarkdownView);
    if (!view) {
      new import_obsidian.Notice("\u274C \u8BF7\u5148\u6253\u5F00\u8981\u5206\u4EAB\u7684\u7B14\u8BB0");
      return null;
    }
    return {
      content: view.editor.getValue(),
      file: view.file
    };
  }
  formatContent(content, title) {
    let text = content;
    if (this.settings.stripFrontmatter) {
      text = text.replace(/^---\n[\s\S]*?\n---\n?/, "");
    }
    if (this.settings.resolveWikiLinks) {
      text = text.replace(/!?\[\[([^\]]*?)(?:\|([^\]]*))?\]\]/g, (match, link, alias) => {
        var _a;
        const isEmbed = match.startsWith("!");
        if (isEmbed) {
          const ext = (_a = link.split(".").pop()) == null ? void 0 : _a.toLowerCase();
          if (["png", "jpg", "jpeg", "gif", "svg", "webp", "bmp"].includes(ext || "")) {
            return `[\u56FE\u7247: ${link}]`;
          }
          return `[\u9644\u4EF6: ${link}]`;
        }
        return (alias == null ? void 0 : alias.trim()) || link.trim();
      });
    }
    text = text.replace(/\n{4,}/g, "\n\n\n");
    if (this.settings.includeTitle && title) {
      text = `# ${title}

${text}`;
    }
    if (this.settings.addSourceTag) {
      text = `${text}

---
\u{1F4DD} \u6765\u81EA Obsidian`;
    }
    return text.trim();
  }
  async shareCurrentNote() {
    var _a, _b;
    const active = this.getActiveContent();
    if (!active)
      return;
    const formatted = this.formatContent(active.content, (_a = active.file) == null ? void 0 : _a.basename);
    if (import_obsidian.Platform.isMobile || import_obsidian.Platform.isIosApp) {
      try {
        await navigator.share({
          title: ((_b = active.file) == null ? void 0 : _b.basename) || "Obsidian \u7B14\u8BB0",
          text: formatted
        });
      } catch (e) {
        if (e instanceof Error && e.name !== "AbortError") {
          new import_obsidian.Notice("\u274C \u5206\u4EAB\u5931\u8D25: " + e.message);
        }
      }
    } else {
      await this.copyToClipboard(formatted);
    }
  }
  async copyForWeChat() {
    var _a;
    const active = this.getActiveContent();
    if (!active)
      return;
    const formatted = this.formatContent(active.content, (_a = active.file) == null ? void 0 : _a.basename);
    await this.copyToClipboard(formatted);
  }
  async copyToClipboard(text) {
    try {
      await navigator.clipboard.writeText(text);
      new import_obsidian.Notice("\u2705 \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F\uFF0C\u8BF7\u5230\u5FAE\u4FE1\u4E2D\u7C98\u8D34");
    } catch (e) {
      const textarea = document.createElement("textarea");
      textarea.value = text;
      document.body.appendChild(textarea);
      textarea.select();
      document.execCommand("copy");
      document.body.removeChild(textarea);
      new import_obsidian.Notice("\u2705 \u5DF2\u590D\u5236\u5230\u526A\u8D34\u677F");
    }
  }
  async shareAsOnlineCard() {
    var _a;
    const active = this.getActiveContent();
    if (!active)
      return;
    const content = this.formatContent(active.content, void 0);
    const title = ((_a = active.file) == null ? void 0 : _a.basename) || "\u65E0\u6807\u9898";
    new import_obsidian.Notice("\u23F3 \u6B63\u5728\u4E0A\u4F20\u7B14\u8BB0...");
    try {
      const url = await this.uploadNote(title, content);
      await this.copyToClipboard(url);
      new import_obsidian.Notice(`\u2705 \u94FE\u63A5\u5DF2\u590D\u5236: ${url}`);
    } catch (err) {
      const msg = err instanceof Error ? err.message : "\u672A\u77E5\u9519\u8BEF";
      new import_obsidian.Notice(`\u274C \u4E0A\u4F20\u5931\u8D25: ${msg}`);
    }
  }
  async uploadNote(title, content) {
    const serverUrl = this.settings.serverUrl.replace(/\/+$/, "");
    const expiry_days = this.settings.defaultExpiryDays;
    const resp = await fetch(`${serverUrl}/api/share`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title, content, expiry_days })
    });
    if (!resp.ok) {
      const text = await resp.text();
      throw new Error(`\u670D\u52A1\u5668\u8FD4\u56DE ${resp.status}: ${text.slice(0, 100)}`);
    }
    const data = await resp.json();
    if (!data.url)
      throw new Error("\u670D\u52A1\u5668\u672A\u8FD4\u56DE\u94FE\u63A5");
    return data.url;
  }
};
var ShareWeChatSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "\u5206\u4EAB\u5230\u5FAE\u4FE1 \u2014 \u8BBE\u7F6E" });
    new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u6807\u9898").setDesc("\u5728\u5206\u4EAB\u5185\u5BB9\u9876\u90E8\u6DFB\u52A0\u7B14\u8BB0\u6807\u9898").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeTitle).onChange(async (value) => {
        this.plugin.settings.includeTitle = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u53BB\u9664 Frontmatter").setDesc("\u79FB\u9664\u7B14\u8BB0\u5F00\u5934\u7684 YAML \u5143\u6570\u636E\u533A").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.stripFrontmatter).onChange(async (value) => {
        this.plugin.settings.stripFrontmatter = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u89E3\u6790\u5185\u90E8\u94FE\u63A5").setDesc("\u5C06 [[\u9875\u9762\u540D]] \u8F6C\u6362\u4E3A\u53EF\u8BFB\u6587\u5B57\uFF0C[\u5D4C\u5165] \u8F6C\u4E3A\u8BF4\u660E\u6807\u8BB0").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.resolveWikiLinks).onChange(async (value) => {
        this.plugin.settings.resolveWikiLinks = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u6DFB\u52A0\u6765\u6E90\u6807\u8BB0").setDesc('\u5728\u672B\u5C3E\u6DFB\u52A0 "\u{1F4DD} \u6765\u81EA Obsidian" \u6807\u8BB0').addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.addSourceTag).onChange(async (value) => {
        this.plugin.settings.addSourceTag = value;
        await this.plugin.saveSettings();
      })
    );
    containerEl.createEl("hr");
    containerEl.createEl("h3", { text: "\u5728\u7EBF\u5361\u7247\u5206\u4EAB" });
    new import_obsidian.Setting(containerEl).setName("\u670D\u52A1\u5668\u5730\u5740").setDesc("\u6258\u7BA1\u7B14\u8BB0\u7684\u670D\u52A1\u5668 URL\uFF08\u9ED8\u8BA4 https://nas.vonxz.cn\uFF09").addText(
      (text) => text.setValue(this.plugin.settings.serverUrl).onChange(async (value) => {
        this.plugin.settings.serverUrl = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian.Setting(containerEl).setName("\u8FC7\u671F\u5929\u6570").setDesc("\u5206\u4EAB\u94FE\u63A5\u7684\u6709\u6548\u5929\u6570\uFF081-30 \u5929\uFF09").addText(
      (text) => text.setValue(String(this.plugin.settings.defaultExpiryDays)).onChange(async (value) => {
        const num = parseInt(value);
        if (num >= 1 && num <= 30) {
          this.plugin.settings.defaultExpiryDays = num;
          await this.plugin.saveSettings();
        }
      })
    );
    containerEl.createEl("hr");
    const usage = containerEl.createEl("div");
    usage.createEl("h3", { text: "\u4F7F\u7528\u8BF4\u660E" });
    usage.createEl("p", {
      text: 'Android \u624B\u673A\uFF1A\u6253\u5F00\u7B14\u8BB0 \u2192 \u70B9\u51FB\u5DE6\u4FA7\u5DE5\u5177\u680F\u7684\u5206\u4EAB\u56FE\u6807\uFF08\u6216\u4F7F\u7528\u547D\u4EE4\u9762\u677F\uFF09\u2192 \u9009\u62E9"\u5206\u4EAB\u5230\u5FAE\u4FE1" \u2192 \u5728\u7CFB\u7EDF\u5206\u4EAB\u83DC\u5355\u4E2D\u9009\u62E9\u5FAE\u4FE1\u3002'
    });
    usage.createEl("p", {
      text: "\u684C\u9762\u7AEF\uFF1A\u4F1A\u81EA\u52A8\u590D\u5236\u5230\u526A\u8D34\u677F\uFF0C\u5728\u5FAE\u4FE1\u4E2D\u7C98\u8D34\u5373\u53EF\u3002"
    });
    usage.createEl("p", {
      text: "\u53EF\u7528\u547D\u4EE4\uFF1A"
    });
    const cmdList = usage.createEl("ul");
    cmdList.createEl("li", { text: "\u5206\u4EAB\u5230\u5FAE\u4FE1 \u2014 \u624B\u673A\u7AEF\u5F39\u51FA\u7CFB\u7EDF\u5206\u4EAB\uFF0C\u684C\u9762\u7AEF\u590D\u5236\u5230\u526A\u8D34\u677F" });
    cmdList.createEl("li", { text: "\u590D\u5236\u7B14\u8BB0\uFF08\u5FAE\u4FE1\u5206\u4EAB\u683C\u5F0F\uFF09\u2014 \u59CB\u7EC8\u590D\u5236\u5230\u526A\u8D34\u677F" });
    cmdList.createEl("li", { text: "\u5206\u4EAB\u4E3A\u5728\u7EBF\u5361\u7247 \u2014 \u4E0A\u4F20\u7B14\u8BB0\u5230\u670D\u52A1\u5668\uFF0C\u751F\u6210\u53EF\u70B9\u51FB\u94FE\u63A5\uFF0C\u81EA\u52A8\u590D\u5236\u5230\u526A\u8D34\u677F" });
  }
};
